// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAji8_WTLyWP5sKPe5rC76YqZDDrbJhhe4',
    appId: '1:447585770292:web:0cc0d06490c95d20796361',
    messagingSenderId: '447585770292',
    projectId: 'quolo-ion',
    authDomain: 'quolo-ion.firebaseapp.com',
    storageBucket: 'quolo-ion.appspot.com',
    measurementId: 'G-71T1SBMBJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdj_P1zqRv4BWArxJhEvL2Xm9Wx7TkF7o',
    appId: '1:447585770292:android:833762e44a463ff2796361',
    messagingSenderId: '447585770292',
    projectId: 'quolo-ion',
    storageBucket: 'quolo-ion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5tdDn5jF809OrtKqUA33N_CTxNsjSfkc',
    appId: '1:447585770292:ios:75a00352d7659fd9796361',
    messagingSenderId: '447585770292',
    projectId: 'quolo-ion',
    storageBucket: 'quolo-ion.appspot.com',
    androidClientId: '447585770292-i47hk1vch69a99mjjiviuhqbe8d4b7l8.apps.googleusercontent.com',
    iosClientId: '447585770292-9cs9h4ef1i5v6s5vqgov6m0r9tu3jmf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5tdDn5jF809OrtKqUA33N_CTxNsjSfkc',
    appId: '1:447585770292:ios:75a00352d7659fd9796361',
    messagingSenderId: '447585770292',
    projectId: 'quolo-ion',
    storageBucket: 'quolo-ion.appspot.com',
    androidClientId: '447585770292-i47hk1vch69a99mjjiviuhqbe8d4b7l8.apps.googleusercontent.com',
    iosClientId: '447585770292-9cs9h4ef1i5v6s5vqgov6m0r9tu3jmf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quolo',
  );
}
